import 'package:flutter/material.dart';

void main() {
  runApp(ColumnApp());
  }

  class ColumnApp extends StatelessWidget {
    @override
      Widget build(BuildContext context) {
          return MaterialApp(
                home: Scaffold(
                        appBar: AppBar(title: Text(' Column App')),
                                body: Center(
                                          child: Column(
                                                      mainAxisAlignment: MainAxisAlignment.center,
                                                                  children: [
                                                                                Container(
                                                                                                height: 100,
                                                                                                                width: 200,
                                                                                                                                color: Colors.blue,
                                                                                                                                                child: Center(
                                                                                                                                                                  child: Text(
                                                                                                                                                                                      'Blue',
                                                                                                                                                                                                          style: TextStyle(color: Colors.white, fontSize: 18),
                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                        SizedBox(height: 20),
                                                                                                                                                                                                                                                                                      Container(
                                                                                                                                                                                                                                                                                                      height: 100,
                                                                                                                                                                                                                                                                                                                      width: 200,
                                                                                                                                                                                                                                                                                                                                      color: Colors.red,
                                                                                                                                                                                                                                                                                                                                                      child: Center(
                                                                                                                                                                                                                                                                                                                                                                        child: Text(
                                                                                                                                                                                                                                                                                                                                                                                            'Red',
                                                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(color: Colors.white, fontSize: 18),
                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }